BookPlus/config/routes.rb
BookPlus::Application.routes.draw do

	root :to => 'welcome#index'

	mount Ckeditor::Engine => '/ckeditor'

	devise_for :users

	post "versions/:id/restore" => "versions#restore", :as => "restore_version"
	get "versions/:id/diff" => "versions#diff", :as => "diff_version"

	resources :books do
		get 'export', :on => :member
		post 'close', :on => :member
		get 'new_edition', :on => :member
		resources :chapters, :except => [:index]
		resources :chunks, :except => [:index]
	end

	resources :chapters, :except => [:index] do
		resources :chunks, :except => [:index]
	end

end

BookPlus/app/models/chapter.rb
class Chapter < ActiveRecord::Base

	attr_accessible :title, :chapter_number, :description, :book_id, :original_updated_at

	belongs_to :book, inverse_of: :chapters
	has_many :chunks, :as => :chunkable


	validates_presence_of :title, :book_id
	validates :title, :uniqueness => {:scope => :book_id}

	def username
		user.email
	end

	def has_chunks?
		!chunks.empty?
	end

	def max_chunk_position
		has_chunks? ? chunks.max_by(&:position).position : 0
	end
end

BookPlus/app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

	before_filter :authenticate_user!
	before_filter :find_book

	def show
		@chapter = Chapter.find(params[:id])
		respond_to do |format|
			format.html { render_check_template }
			format.json { render json: @chapter }
		end

	end

	def edit
		@chapter = Chapter.find(params[:id])

		render_check_template

	end

	def new
		@chapter = Chapter.new

		respond_to do |format|
			format.html { render_check_template }
			format.json { render json: @chapter }
		end
	end

	def create
		@chapter = Chapter.new(params[:chapter])
		@chapter.book = @book

		respond_to do |format|
			if @chapter.save
				format.html { redirect_to @book, notice: I18n.t('views.chapter.flash_messages.book_was_successfully_created') }
				format.json { render json: @chapter, status: :created, location: @chapter }
			else
				format.html { render action: "new" }
				format.json { render json: @chapter.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		@chapter = Chapter.find(params[:id])

		respond_to do |format|
			if (@chapter.update_attributes(params[:chapter]))
				format.html { redirect_to @book, notice: I18n.t('views.chapter.flash_messages.book_was_successfully_updated') }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @chapter.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@chapter = Chapter.find(params[:id])
		@chapter.destroy

		respond_to do |format|
			format.html { redirect_to @book }
			format.json { head :no_content }
		end
	end

	private # all public methods are actions
	def find_book
		@book = Chapter.find(params[:id]).book
	end
end

BookPlus/app/views/chapters/_chapterbar.html.erb
<%= params %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="navbar-form navbar-left" role="add">
	  <% unless @book.closed? %>
		  <%= link_to "edit", edit_book_chapter_path(@book, @chapter), method: :get, :class => "btn btn-primary" %>
		  <%= link_to(raw('create new chunk'), new_chapter_chunk_path(@chapter), :class => "btn btn-primary", :data => {:chapter => @chapter}) %>
	  <% end %>
	</div>
  </div>
</nav>

BookPlus/app/views/chapters/_form.html.erb
<%= form_for ([@book, @chapter]) do |f| %>
	<div class="row">
	  <div class="col-md-9">
		<% if @chapter.errors.any? %>
			<div id="error_explanation">
			  <h2><%= t 'activerecord.errors.template.header', :model => Chapter.model_name.human, :count => @chapter.errors.count %></h2>
			  <ul>
				<% @chapter.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			  </ul>
			</div>
		<% end %>

		<div class="field div-left">
		  <%= f.label :title %>
		  <br/>
		  <%= f.text_field :title %>
		</div>

		<div class="field div-left">
		  <%= f.label :chapter_number %>
		  <br/>
		  <%= f.number_field :chapter_number %>
		</div>
		<div class="field">
		  <%= f.label :description %>
		  <br/>
		  <%= f.text_field :description %>
		</div>
	  </div>
	</div>

	<hr class="featurette-divider">

	<div class="actions">
	  <%= f.submit :class => "btn btn-primary" %>
	</div>
<% end %>

BookPlus/app/views/chapters/edit.html.erb
<%= params %>
<div id="partial-page-wrapper">

  <div class="col-lg-12">
	<h1 id="buttons" class="page-header">Editing chapters</h1>

	<div class="panel panel-default">
	  <div class="panel-body">
		<%= render 'form' %>
	  </div>
	</div>

	<ul class="pager">
	  <%= button_to 'back', book_path(@book), :method => :get, :class => "btn btn-primary" %>
	</ul>
  </div>
</div>

BookPlus/app/views/chapters/new.html.erb
<%= params %>
<div id="partial-page-wrapper">

  <div class="col-lg-12">
	<h1 id="buttons" class="page-header">Create new chapter</h1>

	<div class="panel panel-default">
	  <div class="panel-body">

		<%= render 'form' %>

	  </div>
	</div>

	<ul class="pager">
	  <%= button_to 'back', books_path, method: :get, :class => "btn btn-primary" %>
	</ul>

  </div>

</div>

BookPlus/app/views/chapters/show.html.erb
<%= params %>
<div id="partial-page-wrapper">
  <div class="row">
	<div class="col-lg-12">
	  <div class="page-header">
		<h1 id="Chapter">Chapter: <%= @chapter.title %></h1>
	  </div>
	</div>
  </div>
  <!-- /.row -->

  <div class="row">
	<div class="col-lg-12">
	  <%= render 'chapters/chapterbar' %>
	</div>
  </div>
  <!-- /.row -->

  <div class="row">
	<div class="col-lg-12">
	  <hr class="featurette-divider">
	  <% if @chapter.has_chunks? %>
		  <%= render_chunks(@chapter.chunks, @chapter) %>
	  <% end %>
	</div>
	<!-- /.container-fluid -->
  </div>
  <!-- /.row -->


  <ul class="pager">
	<%= button_to 'back', book_path(@book), :method => :get, :class => "btn btn-primary" %>
  </ul>

</div>