BookPlus/config/routes.rb
BookPlus::Application.routes.draw do

	root :to => 'welcome#index'

	mount Ckeditor::Engine => '/ckeditor'

	devise_for :users

	post "versions/:id/restore" => "versions#restore", :as => "restore_version"
	get "versions/:id/diff" => "versions#diff", :as => "diff_version"

	resources :books do
		get 'export', :on => :member
		post 'close', :on => :member
		get 'new_edition', :on => :member
		resources :chapters, :except => [:index]
		resources :chunks, :except => [:index]
	end

	resources :chapters, :except => [:index] do
		resources :chunks, :except => [:index]
	end

end

BookPlus/app/views/shared/_book_tree.html.erb
<div class="row" id="book_tree">
  <div class="col-lg-12">
	<% if !@book.nil? %>
		<li id="book<%= @book.id %>" class="book" data-closed="<%= @book.closed? %>" data-edit_path="<%= edit_book_path(@book) %>" data-new_chunk_path="<%= new_book_chunk_path(@book) %>">
		  <%= link_to "#{@book.title} (#{@book.edition})", @book %>
		  <ul>
			<% if @book.has_chapters? %>
				<% @book.chapters.each do |chapter| %>
					<li id="chapter<%= chapter.id %>" class="chapter" data-closed="<%= chapter.book.closed? %>" data-edit_path="<%= edit_chapter_path(chapter) %>" data-new_chapter_path="<%= new_book_chapter_path(@book) %>">
					  <%= link_to "#{chapter.title}", chapter %>
					  <ul>
						<% if chapter.has_chunks? %>
							<% chapter.chunks.each do |chunk| %>
								<li id="chunk<%= chunk.id %>" class="chunk" data-delete_path="<%= book_chunk_path(@book, chunk) %>">
								  <%= link_to chunk.title, @book.closed? ? book_path(@book) : edit_book_chunk_path(@book, chunk) %>
								</li>
							<% end %>
						<% end %>
					  </ul>
					</li>
				<% end %>
			<% end %>
			<% @book.chunks.each do |chunk| %>
				<li id="chunk<%= chunk.id %>" class="chunk" data-delete_path="<%= book_chunk_path(@book, chunk) %>">
				  <%= link_to chunk.title, @book.closed? ? book_path(@book) : edit_book_chunk_path(@book, chunk) %>
				</li>
			<% end %>
		  </ul>
		</li>
	<% end %>
  </div>
  <!-- /.col-lg-12 -->
</div> <!-- /.row -->

BookPlus/app/views/shared/_chapters.html.erb
<div class="row">
  <div class="col-lg-12">
	<h2>Chapters</h2>
	<% if @book.has_chapters? %>
		<div class="table-responsive">
		  <table class="table table-bordered table-hover table-striped tablesorter">
			<thead>
			<tr>
			  <th><%= Chapter.human_attribute_name(:title) %></th>
			  <th><%= Chapter.human_attribute_name(:chapter_number) %></th>
			  <th><%= Chapter.human_attribute_name(:book_id) %>
			  <th> edit</th>
			</tr>
			</thead>
			<tbody>
			<% @book.chapters.each do |chapter| %>
				<tr>
				  <td><%= link_to chapter.title, book_chapter_path(@book, chapter) %></td>
				  <td><%= chapter.chapter_number %></td>
				  <td><%= chapter.book_id %></td>
				  <td><%= link_to "edit", @book.closed? ? book_chapter_path(@book, chapter) : edit_book_chapter_path(@book, chapter), method: :get %></td>
				</tr>
			<% end %>
			</tbody>
		  </table>
		</div>
	<% else %>
		<div class="col-lg-4">
		  <div class="alert alert-dismissable alert-danger">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<strong><p><%= 'no chapters' %></p></strong>
		  </div>
		</div>
	<% end %>
  </div>
  <!-- /.col-lg-12-->
</div> <!-- /.row -->

BookPlus/app/views/shared/_chunks.html.erb
<%= context.instance_of? Book %>
<div class="row">
  <div class="col-lg-12">
	<h2>Chunks</h2>

	<div class="table-responsive">
	  <table class="table table-striped table-bordered table-hover tablesorter">
		<thead>
		<tr>
		  <th><%= Chunk.human_attribute_name(:title) %></th>
		  <th><%= Chunk.human_attribute_name(:section) %></th>
		  <th><%= Chunk.human_attribute_name(:chunkable_type) %>
		  <th><%= Chunk.human_attribute_name(:chunkable) %>
		  <th><%= Chunk.human_attribute_name(:version) %>
			<i class="fa fa-sort"></i></th>
		  <th>created_at <i class="fa fa-sort"></i></th>
		  <th> edit</th>
		</tr>
		</thead>
		<tbody class="searchable">
		<% chunks.each do |chunk| %>
			<tr>
			  <td><%= link_to chunk.title, (context.instance_of? Book) ? book_chunk_path(context, chunk) : chapter_chunk_path(context, chunk) %></td>
			  <td><%= chunk.section %></td>
			  <td><%= chunk.chunkable_type.to_s %></td>
			  <td><%= chunk.chunkable_id.to_s %></td>
			  <td><%= chunk.versions.last.id unless chunk.versions == nil %></td>
			  <td><%= chunk.created_at %></td>
			  <td><%= link_to "edit", (context.instance_of? Book) ? edit_book_chunk_path(context, chunk) : edit_book_chunk_path(context, chunk) %></td>
			</tr>
		<% end %>
		</tbody>
	  </table>
	</div>
  </div>
  <!-- /.col-lg-12 -->

</div> <!-- /.row -->