BookPlus/config/routes.rb
BookPlus::Application.routes.draw do

	root :to => 'welcome#index'

	mount Ckeditor::Engine => '/ckeditor'

	devise_for :users

	post "versions/:id/restore" => "versions#restore", :as => "restore_version"
	get "versions/:id/diff" => "versions#diff", :as => "diff_version"

	resources :books do
		get 'export', :on => :member
		post 'close', :on => :member
		get 'new_edition', :on => :member
		resources :chapters, :except => [:index]
		resources :chunks, :except => [:index]
	end

	resources :chapters, :except => [:index] do
		resources :chunks, :except => [:index]
	end

end

BookPlus/app/models/book.rb
class Book < ActiveRecord::Base

	attr_accessible :title, :edition, :published, :genre, :abstract, :tags, :user_ids, :closed

	validates_presence_of :title, :edition
	validates :edition, :uniqueness => {:scope => :title}

	before_destroy :destroy_chunks

	has_and_belongs_to_many :users
	has_many :chapters, inverse_of: :book
	has_many :chunks, :as => :chunkable

	def sliced_attributes
		attributes.slice('title', 'genre', 'abstract', 'tags')
	end

	def published?
		!published.nil?
	end

	def has_chunks?
		!chunks.empty?
	end

	def has_chapters?
		!chapters.empty?
	end

	def max_chunk_position
		has_chunks? ? chunks.max_by(&:position).position : 0
	end

	def users_list
		users.collect { |u| u.username }.join(',')
	end

	def users_list_real_names
		users.collect { |u| u.first_name + ' ' + u.last_name }.join(',')
	end

	private
	def destroy_chunks
		chunks.each do |chunk|
			chunk.destroy
		end
	end

end

BookPlus/app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_filter :authenticate_user!
	before_filter :find_all_users, :only => [:new, :edit, :new_edition]

	@users = User.all

	# GET /books
	# GET /books.json

	def index
		@users = User.all
		@books = current_user.books

		respond_to do |format|
			format.html # diff.html.erb.erb
			format.json { render json: @books }
		end
	end

	# GET /books/1
	# GET /books/1.json
	def show
		@users = User.all
		@book = Book.find(params[:id])

		respond_to do |format|
			format.html { render_check_template }
			format.json { render json: @book }
		end
	end

	def export
		@users = User.all
		@book = Book.find(params[:id])

		respond_to do |format|
			format.pdf do
				render :pdf => @book.title, :layout => 'print'
			end
		end

	end

	# GET /books/new
	# GET /books/new.json
	def new
		@users = User.all
		@book = Book.new

		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @book }
		end
	end

	# GET /books/1/edit
	def edit
		@users = User.all
		@book = Book.find(params[:id])

		unless @book.closed?
			render_check_template
		else
			flash[:error] = I18n.t('views.book.flash_errors.book_is_closed')
			render_check_template 'show'
		end
	end

	# POST /books
	# POST /books.json
	def create
		@users = User.all
		@book = Book.new(params[:book])

		old_book_id = session[:old_book_id]

		respond_to do |format|
			if @book.save
				unless old_book_id.nil?
					old_book = Book.find(old_book_id)
					old_book.chunks.each do |old_chunk|
						chunk = Chunk.new(old_chunk.sliced_attributes)
						chunk.book = @book
						chunk.save
						@book.chunks << chunk
					end
					session[:old_book_id] = nil
				end
				format.html { redirect_to @book, notice: I18n.t('views.book.flash_messages.book_was_successfully_created') }
				format.json { render json: @book, status: :created, location: @book }
			else
				format.html do
					@users ||= User.all
					render action: 'new'
				end
				format.json { render json: @book.errors, status: :unprocessable_entity }
			end
		end
	end

	# PUT /books/1
	# PUT /books/1.json
	def update
		@users = User.all
		@book = Book.find(params[:id])

		if params[:update_chunk_order_only] == 'true'
			chunk_ids = params[:chunk_order].split(',')
			chunk_ids.each_with_index do |chunk_id, i|
				chunk = Chunk.find(chunk_id)
				chunk.update_attribute(:position, i)
			end
		else
			params[:book][:user_ids] ||= []
		end

		respond_to do |format|
			if params[:update_chunk_order_only] == 'true'
				format.html { render 'show', layout: false }
			else
				if @book.update_attributes(params[:book])
					format.html { redirect_to @book, notice: I18n.t('views.book.flash_messages.book_was_successfully_updated') }
					format.json { head :no_content }
				else
					format.html { render action: "edit" }
					format.json { render json: @book.errors, status: :unprocessable_entity }
				end
			end
		end
	end

	def close
		@users = User.all
		@book = Book.find(params[:id])

		respond_to do |format|
			if @book.update_attributes(:closed => true, :published => Time.now)
				format.html { redirect_to @book, notice: I18n.t('views.book.flash_messages.book_was_successfully_closed') }
				format.json { head :no_content }
			else
				format.html { render action: "edit" }
				format.json { render json: @book.errors, status: :unprocessable_entity }
			end
		end
	end

	def new_edition
		@users = User.all
		old_book = Book.find(params[:id])
		@book = Book.new(old_book.sliced_attributes)
		@book.users = old_book.users

		session[:old_book_id] = old_book.id
		render 'new'
	end

# DELETE /books/1
# DELETE /books/1.json
	def destroy
		@users = User.all
		@book = Book.find(params[:id])
		@book.destroy

		respond_to do |format|
			format.html { redirect_to books_url }
			format.json { head :no_content }
		end
	end


end

BookPlus/app/helpers/books_helper.rb
module BooksHelper


end

BookPlus/app/views/books/_bookbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="navbar-form navbar-left" role="edit">
	  <% unless @book.closed? %>
		  <%= link_to "edit", edit_book_path(@book), method: :get, :class => "btn btn-primary" %>
		  <%= link_to "finished", close_book_path(@book), data: {confirm: I18n.t('views.book.close.sure')}, :class => "btn btn-primary" %>
	  <% end %>
	</div>
	<div class="navbar-form navbar-left" role="create">
	  <% unless @book.closed? %>
		  <%= link_to(raw('create new chapter'), new_book_chapter_path(@book), :class => "btn btn-primary", :data => {:book => @book}) %>
		  <%= link_to(raw('create new chunk'), new_book_chunk_path(@book), :class => "btn btn-primary") %>
	  <% end %>
	</div>
	<div class="navbar-form navbar-left" role="extras">
	  <%= link_to "new edition", new_edition_book_path(@book), method: :get, :class => "btn btn-primary" %>
	  <%= link_to "export pdf", export_book_path(@book, :format => 'pdf'), method: "get", :class => "btn btn-primary" %>
	  <%= link_to "delete", @book, method: :delete, data: {confirm: I18n.t('views.are_you_sure')}, :class => "btn btn-primary" %>
	</div>
  </div>
</nav>

BookPlus/app/views/books/_books_tree.html.erb
<div id="books_tree">
  <ul>
    <% books.each do |book| %>
        <li id="book<%= book.id %>" class="book" data-closed="<%= book.closed? %>" data-edit_path="<%= edit_book_path(book) %>" data-new_chunk_path="<%= new_book_chunk_path(book) %>"><%= link_to "#{book.title} (#{book.edition})", book %>
          <ul>
            <% book.chunks.each do |chunk| %>
                <li id="chunk<%= chunk.id %>" class="chunk" data-delete_path="<%= book_chunk_path(book, chunk) %>"><%= link_to chunk.title, book.closed? ? book_chunk_path(book, chunk) : edit_book_chunk_path(book, chunk) %></li>
            <% end %>
          </ul>
        </li>
    <% end %>
  </ul>
</div>

BookPlus/app/views/books/_form_edit.html.erb
<%= form_for(@book) do |f| %>
	<div class="row">
	  <div class="col-md-9">
		<div class="field div-left">
		  <%= f.label :title %>
		  <br/>
		  <%= f.text_field :title %>
		</div>

		<div class="field div-left">
		  <%= f.label :genre %>
		  <br/>
		  <%= f.text_field :genre %>
		</div>

		<div class="field">
		  <%= f.label :edition %>
		  <br/>
		  <%= f.number_field :edition %>
		</div>

		<hr class="featurette-divider">

		<div class="field div-left">
		  <%= f.label :tags %>
		  <br/>
		  <%= f.text_field :tags %>
		</div>

		<div class="field">
		  <%= f.label :published %>
		  <br/>
		  <%= f.date_select :published %>
		</div>

		<hr class="featurette-divider">

		<div class="field">
		  <%= f.label :abstract %>
		  <br/>
		  <%= f.cktext_area :abstract %>
		</div>
	  </div>

	  <div class="col-md-3">
		<div class="field">
		  <%= f.label :users %>
		  <br/>
		  <% @users.each do |user| %>
			  <div>
				<%= check_box_tag "book[user_ids][]", user.id, @book.users.include?(user) %>
				<%= user.email %>
			  </div>
		  <% end %>
		</div>
	  </div>
	</div>
	<hr class="featurette-divider">

	<div class="actions">
	  <%= f.submit :class => "btn btn-primary" %>
	</div>
<% end %>

BookPlus/app/views/books/_form_new.html.erb
<%= form_for(@book) do |f| %>
	<div class="row">
	  <div class="col-md-9">
		<div class="field div-left">
		  <%= f.label :title %>
		  <br/>
		  <%= f.text_field :title %>
		</div>

		<div class="field div-left">
		  <%= f.label :genre %>
		  <br/>
		  <%= f.text_field :genre %>
		</div>

		<div class="field">
		  <%= f.label :edition %>
		  <br/>
		  <%= f.number_field :edition %>
		</div>

		<hr class="featurette-divider">

		<div class="field div-left">
		  <%= f.label :tags %>
		  <br/>
		  <%= f.text_field :tags %>
		</div>

		<div class="field">
		  <%= f.label :published %>
		  <br/>
		  <%= f.date_select :published %>
		</div>

		<hr class="featurette-divider">

		<div class="field">
		  <%= f.label :abstract %>
		  <br/>
		  <%= f.cktext_area :abstract %>
		</div>
	  </div>

	  <div class="col-md-3">
		<div class="field">
		  <%= f.label :users %>
		  <% @users.each do |user| %>
			  <div>
				<%= check_box_tag "book[user_ids][]", user.id, (user == current_user) %>
				<%= user.email %>
			  </div>
		  <% end %>
		</div>
	  </div>
	</div>

	<hr class="featurette-divider">

	<div class="actions">
	  <%= link_to "Back", books_path, method: "get", :class => "btn btn-primary" %>
	  <%= f.submit :class => "btn btn-primary" %>
	</div>

<% end %>

BookPlus/app/views/books/_indexbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  <div class="navbar-form navbar-left" role="add">
		<%= link_to "create new book", new_book_path, method: "get", :class => "btn btn-primary" %>
	  </div>
	</div>
  </div>
</nav>

BookPlus/app/views/books/_modal_show.html.erb
<!-- Modal  Wird von mir nicht benutzen, man kann nicht mit der Implementierung gleichzeitig an mehrere Bücher arbeiten. -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
	<div class="modal-content">
	  <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title" id="myModalLabel">Information</h4>
	  </div>
	  <div class="modal-body">
		<dl class="dl-horizontal">
		  <dt>Edition:</dt>
		  <dd class="book-edition"><%= @book.edition %></dd>
		  <dt>Published:</dt>
		  <dd class="book-published"><%= @book.published %></dd>
		  <dt>Genre:</dt>
		  <dd class="book-genre"><%= @book.genre %></dd>
		  <dt>Tags:</dt>
		  <dd class="book-tags"><%= @book.tags %></dd>
		  <dt>Abstract:</dt>
		  <dd>
			<div class="jumbotron">
			  <div class="container book-abstract">
				<%= raw @book.abstract %>
			  </div>
			</div>
		  </dd>
		</dl>
	  </div>

	  <div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		<button type="button" class="btn btn-default book-edit">Edit</button>
	  </div>
	</div>
  </div>
</div>

<div class="modal fade" id="myModalEdit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
	<div class="modal-content">
	  <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title" id="myModalLabel">Information</h4>
	  </div>
	  <div class="modal-body">
		<%= render "books/form_edit" %>
	  </div>
	  <div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		<button type="button" class="btn btn-primary book-save">Save</button>
	  </div>
	</div>
  </div>
</div>

BookPlus/app/views/books/_overlayNewBook.html.erb
<!-- Modal  Wird von mir nicht benutzen, man kann nicht mit der Implementierung gleichzeitig an mehrere Bücher arbeiten. -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
	<div class="modal-content">
	  <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title" id="myModalLabel">Create new book</h4>
	  </div>
	  <div class="modal-body">
		<%= render "books/form_new" %>
	  </div>
	  <div class="modal-footer">
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		<button type="button" class="btn btn-primary" id="submit-book">Create</button>
	  </div>
	</div>
  </div>
</div>

BookPlus/app/views/books/edit.html.erb
<div id="partial-page-wrapper">
  <div class="col-lg-12">
	<h1 id="buttons" class="page-header">Edit book</h1>

	<div class="panel panel-default">
	  <div class="panel-body">
		<%= render "books/form_edit" %>
	  </div>
	</div>
	<ul class="pager">
	  <%= button_to 'back', book_path(@book), :method => :get, :class => "btn btn-primary" %>
	</ul>
  </div>
</div>

BookPlus/app/views/books/export.pdf.erb
<div id="partial-page-wrapper">
  <div class="col-lg-12">
	<h1 id="buttons" class="page-header">PDF-Export</h1>

	<div class="panel panel-default">
	  <div class="panel-body">
		<div class="cover">
		  <p class="title"><%= @book.title %></p>

		  <p class="authors"><%= @book.users_list_real_names %></p>
		  <br/>
		  <br/>

		  <p><%= "#{@book.edition}. #{Book.human_attribute_name(:edition)}" %></p>
		  <% if @book.published? %>
			  <p><%= "#{I18n.t('views.book.export.published_on')} #{@book.published.to_s}" %></p>
		  <% end %>
		</div>

		<div class="chapter">
		  <h1><%= Book.human_attribute_name(:abstract) %></h1>

		  <p><%= raw @book.abstract %></p>
		</div>

		<% if @book.has_chapters? %>
			<% @book.chapters.each do |chapter| %>
				<div class="chapter">
				  <h1><%= chapter.title %></h1>
				</div>
				<% if chapter.has_chunks? %>
					<% chapter.chunks.each do |chunk| %>
						<div class="chunks">
						  <h1><%= chunk.title %></h1>
						  <%= raw chunk.content %>
						</div>
					<% end %>
				<% end %>
			<% end %>
		<% end %>

		<% if @book.has_chunks? %>
			<% @book.chunks.each do |chunk| %>
				<div class="chunks">
				  <h1><%= chunk.title %></h1>
				  <%= raw chunk.content %>
				</div>
			<% end %>
		<% end %>
	  </div>
	</div>
  </div>
</div>

BookPlus/app/views/books/index.html.erb
<div id="partial-page-wrapper">
  <div class="row">
	<div class="col-lg-12">
	  <div class="page-header">
		<h1 id="Books">Books</h1>
	  </div>
	</div>
  </div>
  <!-- /.row -->

  <div class="col-lg-12 col-sm-11 responsive">

	<%= render 'books/indexbar' %>

	<hr class="featurette-divider">

	<table class="table" id="table">
	  <thead>
	  <tr>
		<th><%= Book.human_attribute_name(:title) %></th>
		<th><%= Book.human_attribute_name(:edition) %></th>
		<th><%= Book.human_attribute_name(:published) %></th>
		<th><%= Book.human_attribute_name(:genre) %></th>
		<th><%= Book.human_attribute_name(:tags) %></th>
		<th><%= Book.human_attribute_name(:users) %></th>
	  </tr>
	  </thead>
	  <tbody class="searchable">
	  <% @books.each do |book| %>
		  <tr>
			<td><%= link_to book.title, book %></td>
			<td><%= book.edition %></td>
			<td><%= book.published %></td>
			<td><%= book.genre %></td>
			<td><%= book.tags %></td>
			<td><%= book.users_list_real_names %></td>
		  </tr>
	  <% end %>
	  </tbody>
	</table>
  </div>
  <!-- /.responsive-->
</div>

BookPlus/app/views/books/new.html.erb
<div id="partial-page-wrapper">
  <div class="col-lg-12">
	<h1 id="buttons" class="page-header">Create new books</h1>

	<div class="panel panel-default">
	  <div class="panel-body">
		<%= render "books/form_new" %>
	  </div>
	</div>
  </div>
</div>

BookPlus/app/views/books/show.html.erb
<%= params %>
<div id="partial-page-wrapper">

  <div class="row">
	<div class="col-lg-12">
	  <div class="page-header">
		<h1 id="Book">Book: <%= @book.title %></h1>
	  </div>
	</div>
  </div>
  <!-- /.row -->

  <div class="col-lg-12 text-left">
	<h1>Details</h1>

	<div class="row">
	  <div class="col-lg-12">
		<%= render 'books/bookbar' %>
	  </div>
	</div>
	<!-- /.row -->

	<div class="row">
	  <div class="col-lg-12">
		<p>
		  <b><%= Book.human_attribute_name(:edition) %>:</b>
		  <%= @book.edition %>
		</p>

		<% if @book.published? %>
			<p>
			  <b><%= Book.human_attribute_name(:published) %>:</b>
			  <%= @book.published %>
			</p>
		<% end %>

		<p>
		  <b><%= Book.human_attribute_name(:genre) %>:</b>
		  <%= @book.genre %>
		</p>

		<p>
		  <b><%= Book.human_attribute_name(:tags) %>:</b>
		  <%= @book.tags %>
		</p>

		<p>
		  <b><%= Book.human_attribute_name(:users) %>:</b>
		  <%= @book.users_list_real_names %>
		</p>
	  </div>

	  <hr class="featurette-divider">
	  <%= render partial: 'shared/book_tree', :locals => {:books => user_books} %>
	  <hr class="featurette-divider">
	  <%= render partial: 'shared/chapters', :locals => {:book => @book} %>
	  <hr class="featurette-divider">
	  <% if @book.has_chunks? %>
		  <%= render_chunks(@book.chunks, @book) %>
	  <% end %>

	</div>
	<!-- /.col-lg-12-->
  </div>
  <!-- /.row -->


  <ul class="pager">
	<%= link_to 'Back', books_path, :class => "btn btn-primary" %>
  </ul>

</div>
</div>