BookPlus/config/routes.rb
BookPlus::Application.routes.draw do

	root :to => 'welcome#index'

	mount Ckeditor::Engine => '/ckeditor'

	devise_for :users

	post "versions/:id/restore" => "versions#restore", :as => "restore_version"
	get "versions/:id/diff" => "versions#diff", :as => "diff_version"

	resources :books do
		get 'export', :on => :member
		post 'close', :on => :member
		get 'new_edition', :on => :member
		resources :chapters, :except => [:index]
		resources :chunks, :except => [:index]
	end

	resources :chapters, :except => [:index] do
		resources :chunks, :except => [:index]
	end

end

BookPlus/app/models/chunk.rb
class Chunk < ActiveRecord::Base

	has_paper_trail :ignore => [:position]

	default_scope { order('position ASC') }

	attr_accessible :title, :section, :content, :user_id, :chunkable, :position, :original_updated_at

	belongs_to :user
	belongs_to :chunkable, polymorphic: true

	before_validation { self.position ||= chunkable_max_chunk_position }


	validates_presence_of :title, :chunkable_id, :chunkable_type, :position
	validates :title, :uniqueness => {:scope => [:chunkable_id, :chunkable_type]}
	validates :position, :uniqueness => {:scope => [:chunkable_id, :chunkable_type]}
	validate :handle_conflict, only: :update


	def username
		user.email
	end

	def sliced_attributes
		attributes.slice('title', 'section', 'content', 'chunkable_id')
	end

	def original_updated_at
		@original_updated_at || updated_at.to_f
	end

	attr_writer :original_updated_at

	private
	def handle_conflict
		if @conflict || updated_at.to_f > original_updated_at.to_f
			@conflict = true
			@original_updated_at = nil
			errors.add :base, I18n.t('views.chunk.messages.merge_changes')
			changes.each do |attribute, values|
				unless attribute == 'content'
					errors.add attribute, "#{I18n.t('views.chunk.messages.was_changed_to')} #{values.first}."
				else
					errors.add attribute, I18n.t('views.chunk.messages.was_changed')
					self.content = "== #{I18n.t('views.chunk.messages.content_other')} =="
					self.content << values.first
					self.content << "== #{I18n.t('views.chunk.messages.content_own')} =="
					self.content << values.last
				end
			end
		end
	end

	private
	def chunkable_max_chunk_position
		if  self.chunkable_type == "Book"
			chunkable = Book.find(self.chunkable_id)
			chunkable.max_chunk_position + 1
		else
			chunkable = Chapter.find(self.chunkable_id)
			chunkable.max_chunk_position + 1
		end


	end
end

BookPlus/app/controllers/chunks_controller.rb
class ChunksController < ApplicationController

	before_filter :authenticate_user!


	# GET /chunks
	# GET /chunks.json


	def show
		@context = context
		@chunk = context.chunks.find(params[:id])
		respond_to do |format|
			format.html { render_check_template }
			format.json { render json: @chunk }
		end
	end

	def new
		@context = context
		@chunk = @context.chunks.new

		respond_to do |format|
			format.html { render_check_template }
			format.json { render json: @chunk }
		end
	end

	def edit
		@context = context
		@chunk = @context.chunks.find(params[:id])
		render_check_template
	end

	def create
		@context = context
		@chunk = @context.chunks.new(chunk_params)

		respond_to do |format|
			if @chunk.save
				format.html { redirect_to context_url(context), notice: I18n.t('views.chunk.flash_messages.book_was_successfully_created') }
				format.json { render json: @chunk, status: :created, location: @chunk }
			else
				format.html { render action: "new" }
				format.json { render json: @chunk.errors, status: :unprocessable_entity }
			end
		end

	end

	def update
		@context = context
		@chunk = @context.chunks.find(chunk_params)
		if @chunk.update_attributes(chunk_params)
			redirect_to context_url(context), notice: I18n.t('views.chunk.flash_messages.book_was_successfully_updated')
		end
	end

	def destroy
		@chunk = Chunk.find(chunk_params)
		@chunk.destroy

		respond_to do |format|
			format.html { redirect_to context_url(context) }
			format.json { head :no_content }
		end
	end

	def chunks_versions
		@versions = @context.chunks.versions
	end

	private
	def chunk_params
		params.require(:chunk).permit!
	end

	private
	def context
		if params[:chapter_id]
			id = params[:chapter_id]
			Chapter.find(params[:chapter_id])
		else
			params[:book_id]
			id = params[:book_id]
			Book.find(params[:book_id])
		end
	end

	private
	def context_url(context)
		if Book === context
			book_path(context)
		else
			chapter_path(context)
		end
	end

end

BookPlus/app/helpers/chunks_helper.rb
module ChunksHelper

	def create_chunk

	end
end

BookPlus/app/views/chunks/_chunkbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">


	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

	  <div class="navbar-form navbar-left" role="add">
		<%= link_to(raw('diffing'), diff_version_path(), :class => "btn btn-primary", :data => {:versions => @chunk.versions.scoped}) %>
	  </div>
	</div>


  </div>
</nav>

BookPlus/app/views/chunks/_form.html.erb
<%= form_for [@context, @chunk] do |f| %>
	<% if @chunk.errors.any? %>
		<div id="error_explanation">
		  <h2><%= t 'activerecord.errors.template.header', :model => Chunk.model_name.human, :count => @chunk.errors.count %></h2>
		  <ul>
			<% @chunk.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		  </ul>
		</div>
	<% end %>

	<%= f.hidden_field :original_updated_at %>
	<div class="field">
	  <%= f.label :title %>
	  <br/>
	  <%= f.text_field :title %>
	</div>

	<div class="field">
	  <%= f.label :section %>
	  <br/>
	  <%= f.text_field :section %>
	</div>

	<div class="field">
	  <%= f.cktext_area :content %>
	</div>

	<div class="actions">
	  <%= f.submit :class => "btn btn-primary" %>
	</div>
<% end %>

BookPlus/app/views/chunks/edit.html.erb
<%= params %>
<div id="partial-page-wrapper">
  <div class="col-lg-12">
	<h1 id="buttons" class="page-header">Editing chunk</h1>

	<div class="panel panel-default">
	  <div class="panel-body">
		<%= render 'form' %>
	  </div>
	</div>

	<ul class="pager">
	</ul>
  </div>
</div>

BookPlus/app/views/chunks/index.html.erb
<h1>Listing chunks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Section</th>
    <th>Content</th>
    <th>User</th>
    <th>Book</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @chunks.each do |chunk| %>
      <tr>
        <td><%= chunk.title %></td>
        <td><%= chunk.section %></td>
        <td><%= chunk.content %></td>
        <td><%= chunk.user %></td>
        <td><%= chunk.book %></td>
        <td><%= link_to 'Show', chunk %></td>
        <td><%= link_to 'Edit', edit_chunk_path(chunk) %></td>
        <td><%= link_to 'Destroy', chunk, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Chunk', new_chunk_path %>

BookPlus/app/views/chunks/new.html.erb
<%= params %>
<div id="partial-page-wrapper">
  <div class="col-lg-12">
	<h1 id="buttons" class="page-header">Create new chunks</h1>

	<div class="panel panel-default">
	  <div class="panel-body">
		<%= render 'form' %>
	  </div>
	</div>


  </div>
</div>

BookPlus/app/views/chunks/show.html.erb
<%= params %>
<div id="partial-page-wrapper">
  <div class="row">
	<div class="col-lg-12">
	  <div class="page-header">
		<h1 id="Chunk">Chunk: <%= @chunk.title %></h1>
	  </div>
	</div>
  </div>
  <!-- /.row -->


  <div class="row">
	<div class="col-lg-12">
	  <%= render 'chunks/chunkbar' %>
	  <% if @context.has_chunks? %>
		  <div class="table-responsive">
			<table class="table table-bordered table-hover table-striped tablesorter">
			  <thead>
			  <tr>
				<th> id</th>
				<th> user</th>
				<th> create at</th>
				<th> item_type</th>
				<th> item_id</th>
				<th> event</th>
				<th> object</th>
				<th> change</th>
				<th> restore</th>
			  </tr>
			  </thead>
			  <tbody>
			  <% if !@chunk.versions.nil? %>
				  <% version = @chunk.versions.scoped.last %>
				  <tr>
					<td><%= version.id %></td>
					<td><%= User.find(version.whodunnit).email %></td>
					<td><%= version.created_at %></td>
					<td><%= version.item_type %></td>
					<td><%= version.item_id %></td>
					<td><%= version.event %></td>
					<td><%= version.object %></td>
					<td><%= version.object_changes %></td>
					<td><%= link_to "restore", restore_version_path(version), :method => :post %></td>
				  </tr>
			  <% end %>
			  </tbody>
			</table>
		  </div>
		  <!-- /.table-responsive -->
	  <% end %>
	</div>
	<!-- /.col-lg-12-->
  </div>
  <!-- /.row -->

  <ul class="pager">
  </ul>

</div> <!-- /.partial-page-wrapper-->